id: P008060
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:43.564737
source_metadata:
  id: bdr:W1KG21276
  title: ཚིག་རྒྱན་རིག་པའི་སྤྱི་ཁོག་འཕྲུལ་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    84f0062a5c0540d3baddaa556532c9ae:
      image_group_id: I1KG21321
      title: Volume 1 of tshig rgyan rig pa'i spyi khog 'phrul gyi me long /
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
