id: P008060
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21276
  title: ཚིག་རྒྱན་རིག་པའི་སྤྱི་ཁོག་འཕྲུལ་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    b03702674c5544f5b0d4d47a5fdbf24f:
      image_group_id: I1KG21321
      title: ''
      volume_number: 1
      total_pages: 328
ebook_metadata:
  title: ཚིག་རྒྱན་རིག་པའི་སྤྱི་ཁོག་འཕྲུལ་གྱི་མེ་ལོང་།
  author: ''
  sku: P008060
  cover: cover.jpg
  layers:
  - pagination
