id: IF29A810E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:47:39+00:00'
last_modified: '2022-06-08T18:08:43.654106+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21276
  title: ཚིག་རྒྱན་རིག་པའི་སྤྱི་ཁོག་འཕྲུལ་གྱི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0483:
      image_group_id: I1KG21321
      title: Volume 1 of tshig rgyan rig pa'i spyi khog 'phrul gyi me long /
      total_pages: 328
      order: 1
      base_file: 0483.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
